name: eags
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss-gpu=1.8.0
  - cuda-toolkit=12.1
  - pytorch=2.1.2
  - pytorch-cuda=12.1 
  - torchvision=0.16.2

  # Build tools & CMake dependencies
  - cmake=3.22         # OpenCV 3.4 scripts require CMake < 3.28
  - eigen              # header-only; provides Eigen3::Eigen CMake target
  - pybind11           # provides pybind11Config.cmake
  - boost              # (VO needs system + filesystem)
  - pkg-config         # helps CMake find system libraries
  - ninja              # faster builds for pip-installed CUDA extensions

  - pip
  - pip:
      - pybind11==2.13.6
      - open3d==0.18.0
      - wandb
      - trimesh==4.0.10
      - pytorch_msssim
      - torchmetrics
      - tqdm
      - imageio
      - opencv-python
      - plyfile
      - roma
      - einops==0.8.0
      - numpy==1.26.4
      - PyQt5==5.15.11
      - matplotlib==3.8
      - matplotlib-inline
      - evo==1.11.0
      - python-pycg
      - einops
      - setuptools<81
      - git+https://github.com/NaufalGhifari/simple-knn.git
      - git+https://github.com/NaufalGhifari/diff-gaussian-rasterization-w-pose.git
      - git+https://github.com/eriksandstroem/evaluate_3d_reconstruction_lib.git@9b3cc08be5440db9c375cc21e3bd65bb4a337db7
      - git+https://github.com/VladimirYugay/gaussian_rasterizer.git@9c40173fcc8d9b16778a1a8040295bc2f9ebf129
